openapi: 3.0.2
info:
  title: Search API
  description: >-
    This API takes a search query and returns results
  version: 2.0
servers:
  - url: https://example.com
paths:
  /hotel_search:
    post:
      summary: Retrieves hotels near a location
      operationId: hotel_search
      requestBody:
        description: Query
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchInput'
      responses:
        '200':
          description: Successfully got results (may be empty)
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
components:
  schemas:
    SearchInput:
      type: object
      properties:
        city:
          type: string
